def get_config(dataset, missing_rate):
    DATASET_CONFIGS_incomplete = {
        "MSRC-v1": {
            "missing_rate": missing_rate,
            "epochs": 1000,
            "lr": 1e-3,
            "hidden_dim": 256,
            "embed_dim": 128,
            "n_layers": 3,
            "dropout": 0.5,
            "use_att": False,
            "use_res": False,
            "lambda_align": 1.0,
            "lambda_self_rec": 0.5,
            "lambda_comp": 1.0,
            "lambda_cse": 1.0,
            "cse_start_epoch": 50,
            "comp_observed_weight": 0.2,
        },
        "Handwritten": {
            "missing_rate": missing_rate,
            "epochs": 1000,
            "lr": 1e-3,
            "hidden_dim": 256,
            "embed_dim": 128,
            "n_layers": 3,
            "dropout": 0.2,
            "use_att": False,
            "use_res": False,
            "lambda_align": 1.0,
            "lambda_self_rec": 0.5,
            "lambda_comp": 1.0,
            "lambda_cse": 0.3,
            "cse_start_epoch": 0,
            "comp_observed_weight": 0.2,
        },
        "LandUse-21": {
            "missing_rate": missing_rate,
            "epochs": 1000,
            "lr": 1e-3,
            "hidden_dim": 256,
            "embed_dim": 128,
            "n_layers": 3,
            "dropout": 0.3,
            "use_att": True,
            "use_res": True,
            "lambda_align": 1.0,
            "lambda_self_rec": 1.0,
            "lambda_comp": 1.0,
            "lambda_cse": 1.5,
            "cse_start_epoch": 50,
            "comp_observed_weight": 0.2,
        },

        "100leaves": {
            "missing_rate": missing_rate,
            "epochs": 1000,
            "lr": 1e-3,
            "hidden_dim": 512,
            "embed_dim": 256,
            "n_layers": 2,
            "dropout": 0.5,
            "use_att": False,
            "use_res": False,
            "lambda_align": 1.0,
            "lambda_self_rec": 0.5,
            "lambda_comp": 1.0,
            "lambda_cse": 1.0,
            "cse_start_epoch": 50,
            "comp_observed_weight": 0.2,
        },

        "Scene-15": {
            "missing_rate": missing_rate,
            "epochs": 1000,
            "lr": 1e-3,
            "hidden_dim": 256,
            "embed_dim": 128,
            "n_layers": 3,
            "dropout": 0.5,
            "use_att": False,
            "use_res": False,
            "lambda_align": 1.0,
            "lambda_self_rec": 1.0,
            "lambda_comp": 1.0,
            "lambda_cse": 1.0,
            "cse_start_epoch": 50,
            "comp_observed_weight": 0.2,
        },

    }

    DATASET_CONFIGS_complete = {
        "MSRC-v1":
            {
                "missing_rate": missing_rate,
                "epochs": 1000,
                "lr": 1e-3,
                "hidden_dim": 256,
                "embed_dim": 128,
                "n_layers": 3,
                "dropout": 0.2,
                "use_att": False,
                "use_res": False,
                "lambda_align": 1.0,
                "lambda_self_rec": 1.0,
                "lambda_comp": 1.0,
                "lambda_cse": 1.0,
                "cse_start_epoch": 50,
                "comp_observed_weight": 0.2,
            },
        "LandUse-21":
            {
                "missing_rate": missing_rate,
                "epochs": 1000,
                "lr": 1e-3,
                "hidden_dim": 256,
                "embed_dim": 128,
                "n_layers": 3,
                "dropout": 0.2,
                "use_att": False,
                "use_res": False,
                "lambda_align": 1.0,
                "lambda_self_rec": 1.0,
                "lambda_comp": 1.0,
                "lambda_cse": 0.5,
                "cse_start_epoch": 50,
                "comp_observed_weight": 0.2,
            },
        "Handwritten":
            {
                "missing_rate": missing_rate,
                "epochs": 1000,
                "lr": 1e-3,
                "hidden_dim": 256,
                "embed_dim": 128,
                "n_layers": 3,
                "dropout": 0.2,
                "use_att": False,
                "use_res": False,
                "lambda_align": 1.0,
                "lambda_self_rec": 0.1,
                "lambda_comp": 1.0,
                "lambda_cse": 1.4,
                "cse_start_epoch": 50,
                "comp_observed_weight": 0.2,
            },

        "100leaves":
            {
                "missing_rate": missing_rate,
                "epochs": 1000,
                "lr": 1e-3,
                "hidden_dim": 512,
                "embed_dim": 256,
                "n_layers": 2,
                "dropout": 0.2,
                "use_att": False,
                "use_res": False,
                "lambda_align": 1.0,
                "lambda_self_rec": 1.0,
                "lambda_comp": 1.0,
                "lambda_cse": 0.5,
                "cse_start_epoch": 0,
                "comp_observed_weight": 0.2,
            },
        "Scene-15":
            {
                "missing_rate": missing_rate,
                "epochs": 1000,
                "lr": 1e-3,
                "hidden_dim": 256,
                "embed_dim": 128,
                "n_layers": 3,
                "dropout": 0.2,
                "use_att": False,
                "use_res": False,
                "lambda_align": 1.0,
                "lambda_self_rec": 1.0,
                "lambda_comp": 1.0,
                "lambda_cse": 0.5,
                "cse_start_epoch": 50,
                "comp_observed_weight": 0.2,
            },

    }
    if missing_rate > 0:
        DATASET_CONFIGS = DATASET_CONFIGS_incomplete[dataset]
    else:
        DATASET_CONFIGS = DATASET_CONFIGS_complete[dataset]

    return DATASET_CONFIGS


if __name__ == '__main__':
    print()

